[package]
name = "rustarok"
version = "0.1.0"
authors = ["Balázs Bódi <balazs.bodi@accenture.com>"]
edition = "2018"

[dependencies]
gl = "0.12.0"
encoding = "0.2.33"
nalgebra = "0.18.0"
nalgebra-glm = "0.4.0"
rand = "0.6.5"
imgui = "0.0.22"
imgui-opengl-renderer = "0.4.0"
imgui-sdl2 = "0.5.0"
sublime_fuzzy = "0.6.0"

[dependencies.sdl2]
version = "0.32.1"
default-features = false
features = ["image"]